name: Compile Mod
on:
  release:
    types:
      - created
  push:
  pull_request:

permissions:
  contents: write
  id-token: write
  pages: write
  packages: write

jobs:
  lint-and-compile:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2.1.0
        with:
          dotnet-version: "7.0.x"
      - run: dotnet restore ${{ github.event.repository.name }}.sln
      - uses: justalemon/VersionPatcher@v0.7.1
        with:
          version: 2.1.0.${{ github.run_number }}
          use-tag: true
          csproj-files: "**/*.csproj"
      - run: dotnet build ${{ github.event.repository.name }}.sln -c ${{ matrix.configuration }}
        working-directory: ${{ env.GITHUB_WORKSPACE }}
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}.${{ matrix.configuration }}
          path: bin/${{ matrix.configuration }}
  docs:
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    needs:
      - lint-and-compile
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2.1.0
        with:
          dotnet-version: "7.0.x"
      - uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.repository.name }}.Release
          path: bin/Release
      - run: ls -R
        working-directory: bin/Release
      - run: dotnet tool update -g docfx
      - run: docfx docs/docfx.json
      - uses: actions/upload-pages-artifact@v1.0.7
        with:
          path: "docs/_site"
      - uses: actions/deploy-pages@v1.2.4
  deploy:
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'release' }}
    needs:
      - lint-and-compile
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2.1.0
        with:
          dotnet-version: "7.0.x"
      - uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.repository.name }}.Release
          path: bin/Release
      - run: ls -R
        working-directory: bin/Release
      - run: 7z a ${{ github.event.repository.name }}.zip ${{ github.workspace }}/bin/Release/*
      - uses: ncipollo/release-action@v1.10.0
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: ${{ github.event.repository.name }}.zip
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
